orders/urls.py
from django.urls import path

from .views import OrderCreateView

app_name = "orders"

urlpatterns = [
    path("create/", OrderCreateView.as_view(), name="create"),
]

sacola/urls.py
from django.urls import path, include
from .views import cart_add, cart_detail, cart_remove, cart_add_freight
from django.conf import settings

app_name = "sacola"

urlpatterns = [
    path("", cart_detail, name="detail"),
    path("add/<int:product_id>/", cart_add, name="add"),
    path("remove/<int:product_id>/", cart_remove, name="remove"),
    path("add_freight/", cart_add_freight, name="add_freigth")
]

wayweb/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views
from sacola.views import *
from django.conf.urls.static import static
from django.contrib.staticfiles import *
from django.urls import path, include

app_name = "wayweb"

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', user_views.index, name='index'),
    path('my_orders/', user_views.myOrders, name='my_orders'),
    path('masculino/', user_views.masculino, name='masculino'),
    path('feminino/', user_views.feminino, name='feminino'),
    path('produto/', user_views.produto, name='descricao'),
    path('compra/', user_views.compra, name='compra'),
    path('pagamento/', user_views.pagamento, name='pagamento'),
    path('reg/', user_views.gerenciamento, name="gerenciamento"),
    path('register/', user_views.register, name='register'),
    path("sacola/", include('sacola.urls')),
    path('product/', include('produto.urls')),
    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls')),
    path('payments/', include('payments.urls'))
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/cart/cart_detail.html
{% load static %}
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Way Resumo da Compra</title>
    <link rel="stylesheet" type="text/css" href="/static/css/compra.css" media="screen" />
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="/static/css/jquery.offcanvas.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
    {%include 'components/guest/header.html'%}

    <div class="row mt-4 border-bottom border-top border-dark mb-2">
        <div class="col-1"></div>
        <div class="col-10">
            <div class="row mt-2 mb-2">
                <div class="col-2"></div>
                <div class="col-4">
                    <a href="{% url 'masculino' %}" class="button">Masculino</a>
                </div>
                <div class="col-2"></div>
                <div class="col-4">
                    <a href="" class="button">Feminino</a>
                </div>
            </div>
        </div>
        <div class="col-1"></div>
    </div>
    
    <div class="row">
        <div class="col-1"></div>
            <div class="col-10">
                 <div id="localizacao">
                    <label >Sacola de compras</label>
                </div>
                <div id="itens">
                    {% if cart %}
                        <label>{{ cart|length }} item</label>
                    {% endif %}
                </div>
            </div>
        <div class="col-1"></div>
    </div>

    <div class="row" id="distancia">
        <div class="col-1"></div>
        <div class="col-7">
            <div class="row">
                <div class="col-"></div>
                <div class="col-11 ">
                    {% if cart %}
                        {% for item in cart %}
                        {% with product=item.product %}
                        <div>
                            <hr class="linha">
                            <div class="row">
                                <div class="col-3">
                                    <a href="{{ product.get_absolute_url }}">
                                        <img src="/media/{{product.image}}" class="h-100 w-100" alt=""/>
                                    </a>
                                </div>
                                <div class="col-4">
                                    <span class="produto">{{ product.name }}</span>
                                    <div class="form-group mt-5">
                                        <label for="tamanho" id="tamanho">Tamanho:</label>
                                        <span class="font-weight-bold">
                                            {% if item.size == 1 %}
                                                P
                                            {% endif %}
                                            {% if item.size == 2 %}
                                                M
                                            {% endif %}
                                            {% if item.size == 3 %}
                                                G
                                            {% endif %}
                                            {% if item.size == 4 %}
                                                GG
                                            {% endif %}
                                        </p>
                                    </div>    
                                    <div class="form-group mt-4">                                     
                                        <form action="{% url 'sacola:add' product.id %}" method="post" id="quantity_form_{{ product.id }}">
                                            {% csrf_token %}
                                            <label for="quantity" id="quantity">Quantidade:</label>
                                            <select name="quantity" class="ml-0 menu" onchange="$('#quantity_form_{{ product.id }}').submit()"> 
                                                {% for i in 21|get_range %}
                                                    {% if i != 0 %}
                                                        <option value="{{ i }}" {% if i == item.quantity %} selected {% endif %}>{{ i }}</option>
                                                    {% endif %}
                                                {% endfor %}   
                                            </select>
                                            <div style="display: none;">
                                                <input type="text" value={{ item.size }} name="size">
                                            </div>
                                            {{ item.update_quantity_form.override }}
                                        </form>
                                    </div>    
                                </div>
                                <div class="col-2">
                                    <div class="h-100 d-flex justify-content-center align-items-center">
                                        <div class="mt-5">
                                            <span class="preco">R$ {{ item.total_price }}</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-3">
                                    <div class="d-flex">
                                        <form action="{% url 'sacola:remove' product.id %}" class="ml-auto" method="post" id="formTest">
                                            {% csrf_token %}
                                            <button class="bg-transparent border-0 shadow-none">
                                                <image class="ml-auto" src="/static/media/icone-X.png"/>
                                            </button>
                                        </form>
                                    </div>
                                </div>    
                            </div>
                        </div>
                        {% endwith %}
                        {% endfor %}
                    {% else %}
                    <hr class="linha">
                        O carrinho está vazio
                    <hr class="linha">
                    {% endif %}
                </div>
                <div class="col-1"></div>
            </div>
        </div>
        <div class="col-3 border border-dark" style="max-height: 510px;">
            <div class="mt-4">
                <center><span class="titulo ">RESUMO DA COMPRA</span></center>
                <div class="linha1"></div>
                <label id="frete">CALCULE O FRETE</label>
                <form action="{% url 'sacola:add_freigth' %}" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col-6">
                        <div>
                            <input name="cep" id="cep" class="cep" type="text" placeholder="CEP" value="{{ cart.get_cep }}">
                        </div>
                    </div>

                    <div class="col-4">
                        <button class="btn btn-dark text-center text-break btn-block sem-borda">
                            <span id="txtOKr">OK</span>
                    </div>

                    <div class="col-2"></div>
                </div>
                </form>
                <hr class="linha4">
                <div class="row" id="quadro">
                    <div class="col-6">
                        <span id="total">TOTAL</span>
                    </div>
                    <div class="col-6 ">
                        <center><span id="valor">R$ {{ cart.get_total_price }}</span></center>
                    </div>    
                    <div class="col-6">
                        <span id="total">Entrega</span>
                    </div>
                    <div class="col-6 ">
                        <center><span id="valor">R$ {{ cart.get_freigth }}</span></center>
                    </div>
                    
                </div>
            
                <div>
                    <a href="javascript:void(0)" url="{% url 'orders:create' %}" id="createOrder" class="btn btn-dark text-center text-break btn-block sem-borda mb-2 btn-finaliza" id="finalizar">Finalizar compra</a>
                </div>
                <div>
                    <a href="{% url 'index' %}" class="btn btn-light text-center text-break btn-block border-dark sem-borda mb-3 btn-escolher" id="escolher">Escolher mais Produtos</a>
                </div>
            </div>
        </div>
        <div class="col-1" ></div>
    </div>  
    
    {%include 'components/guest/rodape.html'%}

    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/velocity.min.js"></script>
    <script src="/static/js/jquery.offcanvas.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <script>
        $('#createOrder').on('click', (e) => {
            e.preventDefault;

            cep = $('#cep');

            if(cep.val()) {
                window.location = $('#createOrder').attr('url');
            } else {
                alert('Calcule seu frete antes de ir na página de compra.');
            }
        })
    </script>
</body>
</html>