orders/urls.py
from django.urls import path

from .views import OrderCreateView

app_name = "orders"

urlpatterns = [
    path("create/", OrderCreateView.as_view(), name="create"),
]

produto/urls.py
from django.urls import path, include
from produto.api.viewsets import CategoryViewSet, ProductViewSet
from .views import *
# from .views import ProductDetailView, ProductListView
from rest_framework import routers

app_name = "produto"

route = routers.DefaultRouter()

route.register('categoria', CategoryViewSet, basename="categoria")
route.register('product', ProductViewSet, basename="categoria")

urlpatterns = [
    path("", ProductListView.as_view(), name="list"),
    path("<slug:slug>/", ProductDetailView.as_view(), name="detail"),
    path("category/<slug:slug>/", ProductListView.as_view(), name="list_by_category"),
    path('cadastro/', include(route.urls)),
]

sacola/urls.py
from django.urls import path, include
from .views import cart_add, cart_detail, cart_remove, cart_add_freight
from django.conf import settings

app_name = "sacola"

urlpatterns = [
    path("", cart_detail, name="detail"),
    path("add/<int:product_id>/", cart_add, name="add"),
    path("remove/<int:product_id>/", cart_remove, name="remove"),
    path("add_freight/", cart_add_freight, name="add_freigth")
]

wayweb/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views
from sacola.views import *
from django.conf.urls.static import static
from django.contrib.staticfiles import *
from django.urls import path, include

app_name = "wayweb"

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', user_views.index, name='index'),
    path('my_orders/', user_views.myOrders, name='my_orders'),
    path('masculino/', user_views.masculino, name='masculino'),
    path('feminino/', user_views.feminino, name='feminino'),
    path('produto/', user_views.produto, name='descricao'),
    path('compra/', user_views.compra, name='compra'),
    path('pagamento/', user_views.pagamento, name='pagamento'),
    path('reg/', user_views.gerenciamento, name="gerenciamento"),
    path('register/', user_views.register, name='register'),
    path("sacola/", include('sacola.urls')),
    path('product/', include('produto.urls')),
    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls')),
    path('payments/', include('payments.urls'))
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

produto/models.py
from django.db import models
from django.urls import reverse
from model_utils.models import TimeStampedModel
from autoslug import AutoSlugField

# Create your models here.

class AvailableManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_available=True)

class Category(TimeStampedModel):
    name = models.CharField(max_length=255, unique=True)
    slug = AutoSlugField(unique=True, always_update=False, populate_from="name")

    class Meta:
        ordering = ("name",)
        verbose_name = "category"
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("produto:list_by_category", kwargs={"slug": self.slug})


class Product(TimeStampedModel):
    category = models.ForeignKey(
        Category, related_name="produto", on_delete=models.CASCADE
    )
    name = models.CharField(max_length=255)
    slug = AutoSlugField(unique=True, always_update=False, populate_from="name")
    image = models.ImageField(upload_to="produto/%Y/%m/%d", blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    is_available = models.BooleanField(default=True)
    masculino = models.BooleanField(default=True)
    feminino = models.BooleanField(default=True)

    objects = models.Manager()
    available = AvailableManager()

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("produto:detail", kwargs={"slug": self.slug})


templates/guest/feminino.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="/static/css/masculino.css" media="screen" />
    <title>WAY Masculino</title>
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="/static/css/jquery.offcanvas.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
    {%include 'components/guest/header.html'%}
    
    <div class="row mt-4 border-bottom border-top border-dark mb-2">
        <div class="col-1"></div>
        <div class="col-10">
            <div class="row mt-2 mb-2">
                <div class="col-2"></div>
                <div class="col-4">
                    <a href="{% url 'masculino' %}" class="button">Masculino</a>
                </div>
                <div class="col-2"></div>
                <div class="col-4">
                    <a href="{% url 'feminino' %}" class="button">Feminino</a>
                </div>
            </div>
        </div>
        <div class="col-1"></div>
    </div>

    <div class="row">
        <div class="col-1"></div>
            <div class="col-10">
                 <div id="localizacao">
                    <label >Você está em: </label>
                    <a class="espaco" href="{% url 'index' %}">Início</a>
                    <label class="espaco">></label>
                     <label class="espaco">Feminino</label>
                </div>
            </div>
        <div class="col-1"></div>
    </div>
    
    <div class="row">
        <div class="col-2 text-center">
            <a data-toggle="collapse" href="#categoryCollapse" role="button" aria-expanded="false" aria-controls="categoryCollapse">
                <i class="fa fa-plus" id="categoryCollapseIcon" title="Edit"></i> Categorias
            </a>
    
            <div class="row d-flex justify-content-center">
                <div class="collapse" style="width: 60%;" id="categoryCollapse">
                    <div class="card card-body text-left">
                        {% for category in categories %}
                            <div class="form-check">
                                <input name="categories[]" class="form-check-input" type="checkbox" value="{{ category.id }}" id="{{ category.id }}">
                                <label class="form-check-label" for="{{ category.name }}">
                                    {{ category.name }}
                                </label>
                            </div>
                        {% endfor %}
                      </div>
                </div>
            </div>
        </div>
        <div class="col-10">
            <div class="row">
                {% for product in product_list %}
                <div class="col-4">
                    <div class="mb-5">
                        <center><a href="{{ product.get_absolute_url }}"><img src="/media/{{product.image}}" width="215px" height="217px" alt=""/></a></center>
                        <center><span class="desc-camiseta">{{ product.name }}</span></center>
                        <center><span class="valor">R$ {{ product.price }}</span></center>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-1"></div>
    </div>  
    <div class="row">
        <div class="col-1"></div>
        <div class="col-10">
            {% if product_list.has_other_pages %}
                {% include "pagination.html" with page=product_list %}
            {% endif %}
        </div>
        <div class="col-1"></div>
    </div>   
    
    {%include 'components/guest/rodape.html'%}

    <!-- <nav class="nav-container-favorito" id="favoritos" style="display: none;">
        <header>
            <a>LISTA DE FAVORITOS ESTÁ VAZIA</a>
        </header>
    </nav>

    <nav id="sacola" style="display: none;">
        <header>
            <a>COMPRA</a>
        </header>
        <a href="http://127.0.0.1:8000/pagamento">IR PARA PAGAMENTO</a>
    </nav> -->

    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/velocity.min.js"></script>
    <script src="/static/js/jquery.offcanvas.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    

    <!-- <script>
        var $sacola = $("#sacola");
        var $favorito = $("#favoritos");
        
        var $sacola = $("#sacola").offcanvas({
                origin: "right",
                duration: 400,
                covarage: 500,
                overlay: true,
                effect: 'slide-in-over',
            });

        $("#button-sacola").on("click", function() {
            $favorito.offcanvas("destroy");
            
            var $sacola = $("#sacola").offcanvas({
                origin: "right",
                duration: 400,
                covarage: 500,
                overlay: true,
                effect: 'slide-in-over',
            });

            $sacola.show();
            $favorito.hide();

            $sacola.offcanvas("toggle");
        });

        $("#button-favorito").on("click", function() {
            $sacola.offcanvas("destroy");

            var $favorito = $("#favoritos").offcanvas({
                origin: "right",
                duration: 400,
                covarage: 500,
                overlay: true,
                effect: 'slide-in-over',
            });
            
            $favorito.show();
            $sacola.hide();

            $favorito.offcanvas("toggle");
        });
    </script> -->

     
    <script>
        const categories = new URLSearchParams(window.location.search).get('categories')
        
        const categoryCollapse = $('#categoryCollapse');
        const categoryCollapseIcon = $('#categoryCollapseIcon');
        
        function openCollapse() {
            categoryCollapseIcon.removeClass("fa-plus");
            categoryCollapseIcon.addClass("fa-minus");
        }

        function closeCollapse() {
            categoryCollapseIcon.removeClass("fa-minus");
            categoryCollapseIcon.addClass("fa-plus");
        }

        if (categories) {
            categoriesArray = categories.split(',')
            
            categoriesArray.forEach(element => {
                $("#" + element).prop('checked', true);
            });
        }
        
        
        function applyFilter() {
            let = categoriesString = ''

            $('input[name="categories[]"]:checked').each((index, element) => {
                if (!categoriesString) {
                    categoriesString += element.value;
                } else {
                    categoriesString = categoriesString + ',' + element.value;
                }
            });

            const page = new URLSearchParams(window.location.search).get('page')

            window.location.href = window.location.pathname+"?"+$.param({
                'page':page,
                'categories':categoriesString
            })
        }

        $('input[name="categories[]"]').change((e) => {
            applyFilter()
        })

        categoryCollapse.on('show.bs.collapse', () => {       
            openCollapse()
        })

        categoryCollapse.on('hide.bs.collapse', () => {
            closeCollapse()
        })
    </script>
</body>
</html>

templates/guest/index.html
{% load crispy_forms_tags %}
{% load static %}
{% load product_tags %}
{% csrf_token %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="static/css/index.css" media="screen" />
    <title>WAY</title>
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="static/css/jquery.offcanvas.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
    {%include 'components/guest/header.html'%}
    
    <div class="row mt-4 border-bottom border-top border-dark mb-2">
        <div class="col-1"></div>
        <div class="col-10">
            <div class="row mt-2 mb-2">
                <div class="col-2"></div>
                <div class="col-4">
                    <a href="{% url 'masculino' %}" class="button">Masculino</a>
                </div>
                <div class="col-2"></div>
                <div class="col-4">
                    <a href="{% url 'feminino' %}" class="button">Feminino</a>
                </div>
            </div>
        </div>
        <div class="col-1"></div>
    </div>

    {%include 'components/guest/carroussel.html'%}

    <div class="row informacao-site">
        <div class="col-1"></div>
        <div class="col-10">
            <div class="row">
                <div class="col-4">
                    <center><img src="/static/media/entrega.png" class="img-informacao" alt=""/><span class="text-informacao ml-2">ENVIO PARA TODO BRASIL</span></center>
                </div>
                <div class="col-4">
                    <center><img src="/static/media/Sale.png" class="img-informacao" alt=""/><span class="text-informacao ml-2">MELHORES PREÇOS</span></center>
                </div>
                <div class="col-4">
                    <center><img src="/static/media/parcela.png" class="img-informacao" alt=""/><span class="text-informacao ml-2">PARCELE SUAS COMPRAS</span></center>
                </div>
            </div>
        </div>
        <div class="col-1"></div>
    </div>
    
    <div class="topico">
        <hr class="linha1"><label class="titulo">TA EM ALTA</label><hr class="linha2">
    </div>
    
    <div class="row mb-5">
        <div class="col-1"></div>
        <div class="col-10">
            <div class="row">
                {% for product in product_list|slice:":3" %}
                    <div class="col-4">
                        <center><a href="{{ product.get_absolute_url }}"><img src="/media/{{product.image}}" style="cursor: pointer;" width="215px" height="217px" alt=""/></a></center>
                        <center><span class="desc-camiseta">{{ product.name }}</span></center>
                        <center><span class="valor">R$ {{ product.price }}</span></center>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-1"></div>
    </div>

    
    <div class="topico">
        <hr class="linha1"><label class="titulo">LANÇAMENTO</label><hr class="linha2">
    </div>
    
    <section class="pb-5">
        <div class="container">
            <div class="row justify-content-center align-items-center">
                <div class="col-1">
                    <a class="btn" href="#carouselExampleIndicators2" role="button" data-slide="prev">
                        <i class="fa fa-chevron-left"></i>
                    </a>
                </div>
                <div class="col-10">
                    <div id="carouselExampleIndicators2" class="carousel slide" data-ride="carousel">
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <div class="row">
                                    {% for product in product_list|slice:":3" %}
                                        <div class="col-md-4 mb-3">
                                            <div class="card" style="border:none">
                                                <img alt="100%x280" src="/media/{{product.image}}"   width="215px" height="217px"
                                                    onclick="location.href='{{ product.get_absolute_url }}';" style="cursor: pointer;">
                                                <div class="card-body">
                                                    <label class="desc-camiseta">{{ product.name }}</label>
                                                    <p class="card-text valor">R$ {{ product.price }}</p>
        
                                                </div>
        
                                            </div>
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="carousel-item">
                                <div class="row">
                                    {% for product in product_list|slice:"3:6" %}
                                        <div class="col-md-4 mb-3">
                                            <div class="card" style="border:none">
                                                <img alt="100%x280" src="/media/{{product.image}}"   width="215px" height="217px"
                                                    onclick="location.href='{{ product.get_absolute_url }}';" style="cursor: pointer;">
                                                <div class="card-body">
                                                    <label class="desc-camiseta">{{ product.name }}</label>
                                                    <p class="card-text valor">R$ {{ product.price }}</p>
        
                                                </div>
        
                                            </div>
                                        </div>
                                    {% endfor %}  
                                </div>
                            </div>
                            <div class="carousel-item">
                                <div class="row">
                                    {% for product in product_list|slice:"6:9" %}
                                        <div class="col-md-4 mb-3">
                                            <div class="card" style="border:none">
                                                <img alt="100%x280" src="/media/{{product.image}}"   width="215px" height="217px"
                                                    onclick="location.href='{{ product.get_absolute_url }}';" style="cursor: pointer;">
                                                <div class="card-body">
                                                    <label class="desc-camiseta">{{ product.name }}</label>
                                                    <p class="card-text valor">R$ {{ product.price }}</p>
        
                                                </div>
        
                                            </div>
                                        </div>
                                    {% endfor %}  
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-1">
                    <a class="btn" href="#carouselExampleIndicators2" role="button" data-slide="next">
                        <i class="fa fa-chevron-right"></i>
                    </a>
                </div>
            </div>
        </div>
    </section>
    
    {%include 'components/guest/rodape.html'%}

    <!-- <nav class="nav-container-favorito" id="favoritos" style="display: none;">
        <header>
            <a>LISTA DE FAVORITOS ESTÁ VAZIA</a>
        </header>
    </nav>

    <nav id="sacola" style="display: none;">
        <header>
            <a>COMPRA</a>
        </header>
        <a href="http://127.0.0.1:8000/pagamento">IR PARA PAGAMENTO</a>
    </nav> -->

    <!-- {% if user.is_authenticated %}
    <div>
        <ul>
            <li class="nav-item">
                <a href="{% url 'produto:list' %}" class="nav-link lead mr-4 font-weight-bold">Produtos</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'sacola:detail' %}" class="nav-link lead mr-4 font-weight-bold">Sacola</a>
            </li>
        </ul>
    </div>
    {% endif %} -->

    <script src="static/js/jquery.min.js"></script>
    <script src="static/js/velocity.min.js"></script>
    <script src="static/js/jquery.offcanvas.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

   <!-- <script>
        var $sacola = $("#sacola");
        var $favorito = $("#favoritos");
        
        var $sacola = $("#sacola").offcanvas({
                origin: "right",
                duration: 400,
                covarage: 500,
                overlay: true,
                effect: 'slide-in-over',
            });

        $("#button-sacola").on("click", function() {
            $favorito.offcanvas("destroy");
            
            var $sacola = $("#sacola").offcanvas({
                origin: "right",
                duration: 400,
                covarage: 500,
                overlay: true,
                effect: 'slide-in-over',
            });

            $sacola.show();
            $favorito.hide();

            $sacola.offcanvas("toggle");
        });

        $("#button-favorito").on("click", function() {
            $sacola.offcanvas("destroy");

            var $favorito = $("#favoritos").offcanvas({
                origin: "right",
                duration: 400,
                covarage: 500,
                overlay: true,
                effect: 'slide-in-over',
            });
            
            $favorito.show();
            $sacola.hide();

            $favorito.offcanvas("toggle");
        });
    </script> -->
</body>
</html>



templates/guest/meus_pedidos.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="/static/css/pedido.css" media="screen" />
    <title>WAY Masculino</title>
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="/static/css/jquery.offcanvas.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
{%include 'components/guest/header.html'%}

<div class="row mt-4 border-bottom border-top border-dark mb-2">
    <div class="col-1"></div>
    <div class="col-10">
        <div class="row mt-2 mb-2">
            <div class="col-2"></div>
            <div class="col-4">
                <a href="{% url 'masculino' %}" class="button">Masculino</a>
            </div>
            <div class="col-2"></div>
            <div class="col-4">
                <a href="{% url 'feminino' %}" class="button">Feminino</a>
            </div>
        </div>
    </div>
    <div class="col-1"></div>
</div>

<div class="row mt-5 mb-5">
    <div class="col-1"></div>
    <div class="col-10">
        <span id="pedido">Meus pedidos</span>
    </div>
    <div class="col-1"></div>
</div>

{% for myOrder in myOrders %}
<div class="row" style="background-color: #ccc;">
    <div class="col-1"></div>
    <div class="col-10 border-dark border-top border-bottom">
        <div class="row">
            <div class="col-3">
                <div class=" mt-2 mb-2">
                    <center><span class="codigo ">Código de compra</span></center>
                    <center><span class="codigo-num">{{ myOrder.id }}</span></center>
                </div>
                {%  if myOrder.trackingCode %}
                <div class="border-dark border-top"></div>
                <div class="mt-2 mb-2">
                    <center><span class="codigo pt-5">Código de rastreio</span></center>
                    <center><span class="codigo-num">{{ myOrder.trackingCode }}</span></center>
                </div>
                {% endif %}
            </div>
            <div class="col-6 mt-4">
                <center><span id="status">Status</span></center>
                <center><span id="concluido">
                    <!-- {% if myOrder.paid %}
                        Concluido
                    {% else %}
                        Pendente
                    {% endif %} -->

                    Em andamento
                </span></center>
            </div>
            <div class="col-3 mt-5">
                <a style="color: black;" data-toggle="collapse" href="#order_{{ myOrder.id }}" role="button" aria-expanded="false" aria-controls="order_{{ myOrder.id }}" onclick="toggleImage({{ myOrder.id }})">
                    <span id="detalhe">Ver mais detalhes</span>
                    <img src="/static/media/Vector.png" data-swap="/static/media/up_arrow.png" id="order_{{ myOrder.id }}_image" class="mb-2" alt=""/>
                </a>
            </div>
        </div>
    </div>
    <div class="col-1"></div>
</div>

{% for item in myOrder.items.all %}
<div class="collapse" id="order_{{ myOrder.id }}" style="background-color: #ccc;">
    {% if forloop.counter == 1 %}
    <div class="row">
        <div class="col-1"></div>
        <div class="col-10 border-bottom border-dark">
            <div class="mt-3 mb-2">
                <span id="endereco">Endereço</span>
            </div>
                <span class="endereco">{{ myOrder.address }}</span><br>
                <span class="endereco">CEP: {{ myOrder.postal_code }}</span><br>
                <span class="endereco">Numero: {{ myOrder.number }}</span><br>
                <span class="endereco">Estado: {{ myOrder.state }}</span><br>
            <div class="mb-3"></div>
        </div>
        <div class="col-1"></div>
    </div>
    {% endif %}
        
    <div class="row">
        <div class="col-1"></div>
        <div class="col-10">
        <div class="row border-dark border-bottom">
            <div class="col-2">
                <center>
                    <a href="{{ item.product.get_absolute_url }}">
                        <img src="/media/{{item.product.image}}" class="mt-2 mb-2" alt="" style="cursor: pointer;" width="215px" height="217px"/>
                    </a>
                </center>
            </div>
            <div class="col-10">
                <div class="mt-2 mb-2">
                    <span class="titulo-roupa">{{ item.product.name }}</span><br>
                </div>
                <div class="mt-3">
                    {% if item.size == '1' %}
                    <span class="desc-roupa">Tamanho: P </span><br>
                    {% elif item.size == '2' %}
                    <span class="desc-roupa">Tamanho: M </span><br>
                    {% elif item.size == '3' %}
                    <span class="desc-roupa">Tamanho: G </span><br>
                    {% elif item.size == '4' %}
                    <span class="desc-roupa">Tamanho: GG </span><br>
                    {% endif %}
                    <span class="desc-roupa">Quantidade: {{ item.quantity }}</span><br>
                    <span class="desc-roupa">R$ {{ item.price }}</span>
                </div>
            </div>
        </div>
        </div>
        <div class="col-1"></div>
    </div>
</div>
{% endfor %}
    
<div class="row mb-5" style="background-color: #ccc;">
    <div class="col-1"></div>
    <div class="col-10 border-dark border-bottom">
    <div class="row">
        <div class="col-2">
            <span id="total">FRETE:</span>
        </div>
        <div class="col-8"></div>
        <div class="col-2 mt-1">
            <center><span id="valor">R$ {{ myOrder.freight }} </span></center>
        </div>
        
        <div class="col-2">
            <span id="total">TOTAL:</span>
        </div>
        <div class="col-8"></div>
        <div class="col-2 mt-1">
            <center><span id="valor">R$ {{ myOrder.get_total_price }}</span></center>
        </div>
    </div>
    </div>
    <div class="col-1"></div>
</div>
{% endfor %}
 
{%include 'components/guest/rodape.html'%}


<script src="/static/js/jquery.min.js"></script>
<script src="/static/js/velocity.min.js"></script>
<script src="/static/js/jquery.offcanvas.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


<script>
    function toggleImage(id) {
        var image = $('#order_' + id + '_image');
        var current = image.attr("src");
        var swap = image.attr("data-swap");
        image.attr('src', swap).attr('data-swap', current);
    }
</script>

</body>
</html>